allowBuilds:
  core-js: false
  unrs-resolver: false

overrides:
  "@babel/core": ">=7.29.1 <8.0.0"
  "@isaacs/brace-expansion": ">=5.0.1 <6.0.0"
  "@eslint/eslintrc@3.3.3>ajv": ">=6.14.0 <7.0.0"
  "@stryker-mutator/core@9.4.0>ajv": ">=8.18.0 <9.0.0"
  "body-parser": ">=2.3.0 <3.0.0"
  "brace-expansion@1.x": ">=1.1.18 <2.0.0"
  "brace-expansion@2.x": ">=2.1.4 <3.0.0"
  "braces": ">=3.0.3 <4.0.0"
  "fast-uri": ">=3.1.5 <4.0.0"
  "flatted": ">=3.4.2 <4.0.0"
  "handlebars": ">=4.7.9 <5.0.0"
  "js-yaml@3.x": ">=3.15.1 <4.0.0"
  "js-yaml@4.x": ">=4.3.1 <5.0.0"
  "lodash": ">=4.17.24 <5.0.0"
  "micromatch": ">=4.0.8 <5.0.0"
  "minimatch@3.x": ">=3.1.4 <4.0.0"
  "minimatch@5.x": ">=5.1.8 <6.0.0"
  "minimatch@9.x": ">=9.0.7 <10.0.0"
  "minimatch@10.x": ">=10.2.3 <11.0.0"
  "@eslint/config-array@0.21.1>minimatch": ">=10.2.3 <11.0.0"
  "@typescript-eslint/typescript-estree@8.54.0>minimatch": ">=10.2.3 <11.0.0"
  "@eslint/eslintrc@3.3.3>minimatch": ">=10.2.3 <11.0.0"
  "eslint@9.39.2>minimatch": ">=10.2.3 <11.0.0"
  "eslint-plugin-import@2.32.0>minimatch": ">=10.2.3 <11.0.0"
  "npm-run-all@4.1.5>minimatch": ">=10.2.3 <11.0.0"
  "multer": ">=2.2.0 <3.0.0"
  "path-to-regexp": ">=8.4.0 <9.0.0"
  "picomatch@2.x": ">=2.3.2 <3.0.0"
  "picomatch@4.x": ">=4.0.4 <5.0.0"
  "printf": ">=0.6.1 <1.0.0"
  "qs": ">=6.15.2 <7.0.0"
  "shell-quote": ">=1.8.5 <2.0.0"
  "underscore": ">=1.13.8 <2.0.0"
